spring:
  datasource:
    url: jdbc:mysql://192.168.3.18:3306/stock
    username: stock
    password: stock
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy